### ISSUE TITLE
Multi-View UWP app crashing

### ISSUE THREAD

**Issue by pnp0a03** [sskodje/GifImageSource#1]
It seems that there is an issue with 'multi-view' style UWP. In multi-view style, the app have multi window page, and each window page running with their own thread.
I've put the recreation sample to my onedrive.
http://1drv.ms/1TcJw5l
This sample is based on Microsoft UWP sample 'Multiple Views'. I've add the animated-gif image control to both main and secondary views.
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MultipleViews  

Here is a recreating procedure:
1. Start the App.
2. Click the button 'Create new view'.
3. Select the 'New View' from listbox 'Open views'.
4. Click the button 'Show selected view as standalone'.
5. Secondary view page appears. You can see the animated gif image.
6. Close the secondary page. The focus is backed to the main page, then the app halted and crashed.

**Comment by sskodje** [comment]
Good tidings!
I found the problem. I was twofold. First was using the Dispatcher inside the GifImageView, and when the window closed, the dispatcher was set to nullptr, and it crashed with a null reference exception.

Second problem was caused by using IAsyncAction. Problem went away when replaced with a task, and as a bonus performance improved as well. 

I've updated NuGet with the changes.

**Comment by pnp0a03** [comment]
Hi,
Thank you for your quick response! I've download the version 1.0.2, and I could confirmed that the crash issue was fixed.
But.. unfortunately, I found the another issue. Should I open the new issue?
It seems that.. If the app have only 1 page and the page have many of GiImageSourced image controls, it's ok.
But, If the app have 2 or more multi window pages, and each pages have the GifImageSourced image controls, it crashed with following 2 exceptions.
1. Platform::COMException HRESULT:0x88990016 The push and pop calls were unbalanced.
2. Platform::COMException HRESULT:0x88990001 The object was not in the correct state to process the method.

You can recreate the issue with previous sample project.
If you want more detail about the recreation, please let me know.
best regards,

**Comment by sskodje** [comment]
The problem was that i use a shared directx device context to save a bit of resource when having multiple gifs in the same window. But of course i failed to take into consideration that UWP could actually spawn several windows. And each window needs it's own context, that's why it crashed.

I fixed it so each window now uses it's own context, and it works in my tests at least. 
NuGet should be updated to 1.03.

Thanks a lot for finding these bugs btw!

**Comment by pnp0a03** [comment]
I could confirm that the issue was fixed by 1.0.3. Thank you! You're the man!!
Full test is on going, but it works well on Win10 Desktop - x64 and Win10 Mobile - ARM.
