### ISSUE TITLE
Not handling URIs with a query in the path

### ISSUE THREAD

**Issue by ryanvalentin** [sskodje/GifImageSource#2]
I noticed an issue where some URLs were throwing an exception with the message `The filename, directory name, or volume label syntax is incorrect`. After a little debugging this was happening with URIs that had a query after their extension.

It looks like the [GetFileExtension function](https://github.com/sskodje/GifImageSource/blob/master/GifImage/Shared/Utilities.h#L119) doesn't expect the query, so it returns a file extension with the query in it, e.g. `.gif?w=200`. Because the filename then illegal file path characters, the exception occurs when trying to save to the cache.
### To Reproduce:

Just create an image and try to set an image URI with a query in the path, e.g.:

``` xml
<Image gif:AnimationBehavior.ImageUriSource="https://uploads.disquscdn.com/images/c6aed8d2d4ba77c60eee3f761004fc879c8ad0727419a7dd566081a8dad2fb34.gif?w=200" />
```

It's easy enough to strip the query from the path before setting it, but there might be cases where that changes the resource (size, quality, etc.). It wouldn't necessarily be ideal to save the resource while ignoring the query either, so the best solution could use some discussion.

**Comment by sskodje** [comment]
Thank you for reporting the issue! It seems the problem is isolated to the method that caches the file, and it's not strictly necessary to actually have a file extension for that part. I think i might just remove the extension all together and just save the hash. That way it should work with any file you throw at it, as it checks if it is a valid image or GIF file a bit later anyway.

I'll update NuGet and git right away.

**Comment by ryanvalentin** [comment]
Great, that was fast! I can confirm this works now. This is a great library by the way - saved me a ton of headache
